baseURL = "https://notion-blog-2wg.pages.dev/"
languageCode = "zh-cn"
title = "Padresvater's Blog"
theme = "DoIt"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowToc = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  
# DoIt 新增 | 0.2.14 版权信息
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# 作者配置
[params.author]
  name = "Padresvater"
  email = "padresss512@gmail.com"
  
[params.page.toc]
  # 是否使用目录
  enable = true
  # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
  keepStatic = true
  # 是否使侧边目录自动折叠展开
  auto = true

# DoIt 新增 | 0.2.0 代码配置
[params.page.code]
  # 默认展开显示的代码行数
  maxShownLines = 10
  # 是否显示代码行号
  lineNos = true
  # 是否开启代码换行
  wrap = false
  # 是否显示代码块标题
  header = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # 添加 JSON 输出，用于搜索功能

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15

[params.search]
  enable = true
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  #  最大结果数目
  maxResultLength = 10
  #  结果内容片段长度
  snippetLength = 50
  #  搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  #  是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    #  https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

  # 页面头部导航栏配置
  [params.header]
    # DoIt 新增 | 0.2.11 主题切换模式
    # 主题切换模式 ("switch", "select")
    themeChangeMode = "select"
    # DoIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = ""
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # DoIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = true
      
# DoIt 新增 | 0.2.5 TypeIt 配置
[params.typeit]
  # 每一步的打字速度 (单位是毫秒)
  speed = 100
  # 光标的闪烁速度 (单位是毫秒)
  cursorSpeed = 1000
  # 光标的字符 (支持 HTML 格式)
  cursorChar = "|"
  # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
  duration = -1

# 页面底部信息配置
[params.footer]
  enable = true
  # DoIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
  custom = ''
  # DoIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
  hugo = true
  # DoIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
  # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
  hostedOn = ''
  # DoIt 新增 | 0.2.0 是否显示版权信息
  copyright = true
  # DoIt 新增 | 0.2.0 是否显示作者
  author = true
  # 网站创立年份
  since = 2025
   

# DoIt 新增 | 0.2.0 Section (所有文章) 页面配置
[params.section]
  # section 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # RSS 文章数目
  rss = 10
  # DoIt 新增 | 0.2.13 最近更新文章设置
  [params.section.recentlyUpdated]
    enable = false
    rss = false
    days = 30
    maxCount = 10

# DoIt 新增 | 0.2.0 List (目录或标签) 页面配置
[params.list]
  # list 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # RSS 文章数目
  rss = 10

# 主页配置
[params.home]
  # DoIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱, 用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    # 将你的头像文件放置于 static 或者 assets 目录下
    # 文件路径是相对于 static 或者 assets 目录的
    avatarURL = "/images/avatar.webp"
    # 头像的链接指向的 URL
    avatarLinkURL = ""
    # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题
    subtitle = "这是我的全新 Hugo 网站"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # DoIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false
  # DoIt 更改 | 0.2.0 文章页面的分享信息设置
  [params.page.share]
    enable = true
    Twitter = true
    Linkedin = false
    Reddit = false
    Weibo = true
    Blogger = true
    Baidu = false


# DoIt 更改 | 0.2.0 评论系统设置
  [params.page.comment]
    enable = true
    # Disqus 评论系统设置
    [params.page.comment.disqus]
      # DoIt 新增 | 0.1.1
      enable = false
      # Disqus 的 shortname, 用来在文章中启用 Disqus 评论系统
      shortname = ""
    # Gitalk 评论系统设置
    [params.page.comment.gitalk]
      # DoIt 新增 | 0.1.1
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine 评论系统设置
    [params.page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta= ""
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""
      # DoIt 新增 | 0.2.6 emoji 数据文件名称, 默认是 "google.yml"
      # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
      # 位于 "themes/DoIt/assets/data/emoji/" 目录
      # 可以在你的项目下相同路径存放你自己的数据文件:
      # "assets/data/emoji/"
      emoji = ""
    # Waline 评论系统设置
    [params.page.comment.waline]
      # DoIt 更改 | 0.2.14
      enable = false
      serverURL = ""
      pageview = true
      comment = true
      # emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
      # meta = ['nick', 'mail', 'link']
      # requiredMeta = []
      # login = 'enable'
      # wordLimit = 0
      # pageSize = 10
      # imageUploader = false
      # highlighter = false
      # texRenderer = false
    # Facebook 评论系统设置
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = "zh_CN"
    # DoIt 新增 | 0.2.0 Telegram Comments 评论系统设置
    [params.page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
      dark = false
    # DoIt 新增 | 0.2.0 Commento 评论系统设置
    [params.page.comment.commento]
      enable = false
    # DoIt 新增 | 0.2.5 Utterances 评论系统设置
    [params.page.comment.utterances]
      enable = false
      # owner/repo
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # DoIt 新增 | 0.2.12 Twikoo 评论系统设置
    [params.page.comment.twikoo]
      enable = false
      envId = ""
      region = ""
      path = ""
      cloudbase = true # boolean : true / false. # 是否部署在腾讯云 CloudBase
      visitor = true
      commentCount = true
    # DoIt 新增 | 0.2.12 Vssue 评论系统设置
    [params.page.comment.vssue]
      enable = false
      platform = "" # ("bitbucket", "gitea", "gitee", "github", "gitlab")
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # DoIt 新增 | 0.2.13 Remark42 评论系统设置
    [params.page.comment.remark42]
      enable = false
      host = ""
      site_id = ""
      max_shown_comments = 15
      show_email_subscription = true
      simple_view = false
    # DoIt 新增 | 0.2.13 giscus 评论系统设置
    [params.page.comment.giscus]
      enable = false
      # owner/repo
      dataRepo = ""
      dataRepoId = ""
      dataCategory = ""
      dataCategoryId = ""
      dataMapping = "pathname"
      dataReactionsEnabled = "1"
      dataEmitMetadata = "0"
      dataInputPosition = "bottom"
      lightTheme = "light"
      darkTheme = "dark"
      dataLang = "zh-CN"
      dataLoading = "lazy"
    # artalk 评论系统设置
    [params.page.comment.artalk]
      enable = false
      server = ""
      site = ""
      lite = false
      katex = false
      lightbox = false
      pageview = true
      commentCount = true