baseURL = "https://notion-blog-2wg.pages.dev/"
languageCode = "zh-cn"
title = "Padresvater's Blog"
theme = "DoIt"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowToc = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  
  # 添加搜索功能配置
  ShowSearchButton = true
  
  # 添加评论功能配置
  comments = true
  
[params.page.toc]
  # 是否使用目录
  enable = true
  # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
  keepStatic = true
  # 是否使侧边目录自动折叠展开
  auto = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # 添加 JSON 输出，用于搜索功能

[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15

[params.search]
  enable = true
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  #  最大结果数目
  maxResultLength = 10
  #  结果内容片段长度
  snippetLength = 50
  #  搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  #  是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    #  https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false