version = "0.3.X"
# Section (all posts) page config
# Section (所有文章) 页面配置
[section]
# special amount of posts in each section page
# section 页面每页显示文章数量
paginate = 20
# date format (month and day)
# 日期格式 (月和日)
dateFormat = "01-02"
# amount of RSS pages
# RSS 文章数目
rss = 10
# recently updated posts settings
# 最近更新文章设置
[section.recentlyUpdated]
days = 30
enable = true
maxCount = 10
rss = true

# List (category or tag) page config
# List (目录或标签) 页面配置
[list]
# special amount of posts in each list page
# list 页面每页显示文章数量
paginate = 20
# date format (month and day)
# 日期格式 (月和日)
dateFormat = "01-02"
# amount of RSS pages
# RSS 文章数目
rss = 10

[page]
[page.math]
enable = true
blockLeftDelimiter = "\\["
blockRightDelimiter = "\\]"
inlineLeftDelimiter = "\\("
inlineRightDelimiter = "\\)"
copyTex = true
mhchem = true
[page.toc]
# whether to enable the table of the contents
# 是否使用目录
enable = true
# whether to keep the static table of the contents in front of the post
# 是否保持使用文章前面的静态目录
keepStatic = false
# whether to make the table of the contents in the sidebar automatically collapsed
# 是否使侧边目录自动折叠展开
auto = true

[header]
# desktop header mode ("fixed", "normal", "auto")
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# mobile header mode ("fixed", "normal", "auto")
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# theme change mode ("switch", "select")
# 主题切换模式 ("switch", "select")
themeChangeMode = "select"
# Header title config
# 页面头部导航栏标题配置
[header.title]
# whether to use typeit animation for title name
# 是否为标题显示打字机动画
typeit = true